# Test Values

twitter:
  oauth:
    consumer_key: xvz1evFS4wEEPTGEFPHBog
    nonce: kYjzVBB8Y0ZFabxSWbWovY3uYSQ2pTgmZeNu2VS4cg
    signature_method: HMAC-SHA1
    token: 370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb
    version: 1.0